function plot_Speed(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 18-Dec-2020 15:09:50

% Create figure
figure1 = figure('NumberTitle','off','Name','ABS Speeds');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1);
set(plot1(1),'DisplayName','Vehicle Speed \omega_v');
set(plot1(2),'DisplayName','Wheel Speed \omega_w');

% Create ylabel
ylabel('Speed(rad/sec)');

% Create xlabel
xlabel('Time(sec)');

% Create title
title('Vehicle speed and wheel speed');

box(axes1,'on');
hold(axes1,'off');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','best');

